celeb_names = [
    "girl",
    "hailee steinfeld",
    "jordyn jones",
    "millie bobby brown",
    "sadie sink",
    "sophia lillis"
]

celeb_preset_dict = {
    #Name + age              Body Type | Breasts Size | Ass Size
    #"hailee steinfeld 0":    dict(body_type="fat", boobs_size="flat", ass_size="small"),
    "hailee steinfeld 0":    ["fat",       "flat",      "small"],
    "hailee steinfeld 1":    ["fat",       "flat",      "small"],
    "hailee steinfeld 2":    ["fat",       "flat",      "small"],
    "hailee steinfeld 3":    ["slim",      "flat",      "small"],
    "hailee steinfeld 4":    ["slim",      "flat",      "small"],
    "hailee steinfeld 5":    ["slim",      "flat",      "small"],
    "hailee steinfeld 6":    ["slim",      "flat",      "small"],
    "hailee steinfeld 7":    ["slim",      "flat",      "small"],
    "hailee steinfeld 8":    ["slim",      "flat",      "small"],
    "hailee steinfeld 9":    ["slim",      "flat",      "small"],
    "hailee steinfeld 10":   ["slim",      "flat",      "small"],
    "hailee steinfeld 11":   ["slim",      "flat",      "small"],
    "hailee steinfeld 12":   ["slim",      "small",     "small"],
    "hailee steinfeld 13":   ["slim",      "small",     "small"],
    "hailee steinfeld 14":   ["slim",      "medium",    "small"],
    "hailee steinfeld 15":   ["slim",      "medium",    "small"],
    "hailee steinfeld 16":   ["slim",      "medium",    "small"],
    "hailee steinfeld 17":   ["slim",      "medium",    "small"],
    "hailee steinfeld 18":   ["slim",      "medium",    "small"],
    "hailee steinfeld 19":   ["slim",      "medium",    "small"],
    "hailee steinfeld 20":   ["slim",      "medium",    "small"],
    "hailee steinfeld 21":   ["slim",      "medium",    "small"],
    "hailee steinfeld 22":   ["slim",      "medium",    "small"],
    "hailee steinfeld 23":   ["slim",      "medium",    "small"],
    "hailee steinfeld 24":   ["slim",      "medium",    "small"],
    "hailee steinfeld 25":   ["slim",      "medium",    "small"],
    "hailee steinfeld 26":   ["slim",      "medium",    "small"],
    "hailee steinfeld 27":   ["slim",      "medium",    "small"],
    "hailee steinfeld 28":   ["slim",      "medium",    "small"],

    "jordyn jones 0":        ["fat",       "flat",      "small"],
    "jordyn jones 1":        ["fat",       "flat",      "small"],
    "jordyn jones 2":        ["fat",       "flat",      "small"],
    "jordyn jones 3":        ["petite",    "small",     "small"],
    "jordyn jones 4":        ["petite",    "small",     "small"],
    "jordyn jones 5":        ["petite",    "small",     "small"],
    "jordyn jones 6":        ["petite",    "small",     "small"],
    "jordyn jones 7":        ["petite",    "small",     "small"],
    "jordyn jones 8":        ["petite",    "small",     "small"],
    "jordyn jones 9":        ["petite",    "small",     "small"],
    "jordyn jones 10":       ["petite",    "small",     "small"],
    "jordyn jones 11":       ["petite",    "small",     "small"],
    "jordyn jones 12":       ["petite",    "small",     "small"],
    "jordyn jones 13":       ["petite",    "small",     "small"],
    "jordyn jones 14":       ["petite",    "small",     "small"],
    "jordyn jones 15":       ["petite",    "small",     "small"],
    "jordyn jones 16":       ["petite",    "small",     "small"],
    "jordyn jones 17":       ["petite",    "small",     "small"],
    "jordyn jones 18":       ["petite",    "small",     "small"],
    "jordyn jones 19":       ["petite",    "small",     "small"],
    "jordyn jones 20":       ["petite",    "small",     "small"],
    "jordyn jones 21":       ["petite",    "small",     "small"],
    "jordyn jones 22":       ["petite",    "small",     "small"],
    "jordyn jones 23":       ["petite",    "small",     "small"],
    "jordyn jones 24":       ["petite",    "small",     "small"],

    "millie bobby brown 0":  ["fat",       "flat",      "small"],
    "millie bobby brown 1":  ["fat",       "flat",      "small"],
    "millie bobby brown 2":  ["fat",       "flat",      "small"],
    "millie bobby brown 3":  ["slim",      "flat",      "small"],
    "millie bobby brown 4":  ["slim",      "flat",      "small"],
    "millie bobby brown 5":  ["slim",      "flat",      "small"],
    "millie bobby brown 6":  ["slim",      "flat",      "small"],
    "millie bobby brown 7":  ["slim",      "flat",      "small"],
    "millie bobby brown 8":  ["slim",      "flat",      "small"],
    "millie bobby brown 9":  ["slim",      "flat",      "small"],
    "millie bobby brown 10": ["slim",      "flat",      "small"],
    "millie bobby brown 11": ["slim",      "flat",      "small"],
    "millie bobby brown 12": ["slim",      "small",     "small"],
    "millie bobby brown 13": ["slim",      "small",     "small"],
    "millie bobby brown 14": ["slim",      "small",     "small"],
    "millie bobby brown 15": ["slim",      "small",     "small"],
    "millie bobby brown 16": ["slim",      "small",     "small"],
    "millie bobby brown 17": ["slim",      "medium",    "small"],
    "millie bobby brown 18": ["slim",      "medium",    "small"],
    "millie bobby brown 19": ["slim",      "medium",    "small"],
    "millie bobby brown 20": ["slim",      "big",       "small"],

    "sadie sink 0":          ["fat",       "small",     "small"],
    "sadie sink 1":          ["fat",       "small",     "small"],
    "sadie sink 2":          ["fat",       "small",     "small"],
    "sadie sink 3":          ["slim",      "small",     "small"],
    "sadie sink 4":          ["slim",      "small",     "small"],
    "sadie sink 5":          ["slim",      "small",     "small"],
    "sadie sink 6":          ["slim",      "small",     "small"],
    "sadie sink 7":          ["slim",      "small",     "small"],
    "sadie sink 8":          ["slim",      "small",     "small"],
    "sadie sink 9":          ["slim",      "small",     "small"],
    "sadie sink 10":         ["slim",      "small",     "small"],
    "sadie sink 11":         ["slim",      "small",     "small"],
    "sadie sink 12":         ["slim",      "small",     "small"],
    "sadie sink 13":         ["slim",      "small",     "small"],
    "sadie sink 14":         ["slim",      "medium",    "small"],
    "sadie sink 15":         ["slim",      "medium",    "small"],
    "sadie sink 16":         ["slim",      "medium",    "small"],
    "sadie sink 17":         ["slim",      "medium",    "small"],
    "sadie sink 18":         ["slim",      "medium",    "small"],
    "sadie sink 19":         ["slim",      "medium",    "small"],
    "sadie sink 20":         ["slim",      "medium",    "small"],
    "sadie sink 21":         ["slim",      "medium",    "small"],
    "sadie sink 22":         ["slim",      "medium",    "small"],

    "sophia lillis 0":       ["fat",       "flat",      "small"],
    "sophia lillis 1":       ["fat",       "flat",      "small"],
    "sophia lillis 2":       ["fat",       "flat",      "small"],
    "sophia lillis 3":       ["petite",    "small",     "small"],
    "sophia lillis 4":       ["petite",    "small",     "small"],
    "sophia lillis 5":       ["petite",    "small",     "small"],
    "sophia lillis 6":       ["petite",    "small",     "small"],
    "sophia lillis 7":       ["petite",    "small",     "small"],
    "sophia lillis 8":       ["petite",    "small",     "small"],
    "sophia lillis 9":       ["petite",    "small",     "small"],
    "sophia lillis 10":      ["petite",    "small",     "small"],
    "sophia lillis 11":      ["petite",    "small",     "small"],
    "sophia lillis 12":      ["petite",    "small",     "small"],
    "sophia lillis 13":      ["petite",    "small",     "small"],
    "sophia lillis 14":      ["petite",    "small",     "small"],
    "sophia lillis 15":      ["petite",    "small",     "small"],
    "sophia lillis 16":      ["petite",    "small",     "small"],
    "sophia lillis 17":      ["petite",    "small",     "small"],
    "sophia lillis 18":      ["petite",    "small",     "small"],
    "sophia lillis 19":      ["petite",    "small",     "small"],
    "sophia lillis 20":      ["petite",    "small",     "small"],
    "sophia lillis 21":      ["petite",    "small",     "small"],
    "sophia lillis 22":      ["petite",    "small",     "small"],
}


def select_celeb(celeb_name, age):
    if celeb_name != "girl" and celeb_name != "":
        preset = celeb_preset_dict[f"{celeb_name} {age}"]
        if preset != []:
            body_type = preset[0]
            boobs_size = preset[1]
            ass_size = preset[2]
            return celeb_name, body_type, boobs_size
        else:
            return celeb_name, "Auto", "Auto"
    else:
        return "girl", "Auto", "Auto"